//! Reputation NFT contract.
//!
//! ## Design
//!
//! `ReputationNftContract` is a minimal, purpose-built contract that tracks a
//! per-address reputation score (u32).  It is intentionally separate from the
//! lending contract so that:
//!
//! 1. The lending contract can be upgraded without resetting reputation data.
//! 2. A single reputation contract can potentially service multiple lending
//!    contracts.
//! 3. The contract can be audited and deployed independently.
//!
//! ## Dynamic Yield & `calculate_dynamic_yield`
//!
//! The previous codebase referenced a `calculate_dynamic_yield` function that
//! depended on `ReputationNftExternalClient`.  That function was removed because
//! it depended on a contract that only existed under `#[cfg(test)]`, making it
//! untestable in production.
//!
//! Instead, **yield is now a two-layer system**:
//!
//! - **Static yield** (`total_yield`): locked in at disbursement time from
//!   `Config::yield_bps`.  Vouchers always receive this.
//! - **Compound interest** (`accrued_interest`): computed daily on the
//!   outstanding principal (see `helpers::calculate_daily_compound_interest`).
//!   This replaces "dynamic yield" — it is deterministic and fully on-chain
//!   without any external oracle call.
//!
//! Reputation score (from this contract) can still be read by UIs via
//! `QuorumCreditContract::get_reputation()`, and admins can choose to offer
//! better loan terms off-chain based on reputation history.  On-chain dynamic
//! yield adjustment based on reputation is a future roadmap item that would
//! require a governance vote to update `Config::yield_bps` per borrower.

#![allow(unused)]

use soroban_sdk::{contract, contractclient, contractimpl, contracttype, panic_with_error, Address, Env};
use crate::errors::ContractError;
use crate::types::{ReputationNFTRecord, DataKey};

#[contracttype]
pub enum RepKey {
    Minter,         // Address authorised to mint/burn (the main lending contract)
    Score(Address), // borrower → u32 reputation score
}

/// External client trait — generated by `#[contractclient]` for cross-contract calls.
/// The lending contract uses `ReputationNftExternalClient` to call this contract.
#[contractclient(name = "ReputationNftExternalClient")]
pub trait ReputationNftContractTrait {
    fn initialize(env: Env, minter: Address);
    fn mint(env: Env, to: Address);
    fn burn(env: Env, from: Address);
    fn balance(env: Env, addr: Address) -> u32;
}

/// Production reputation NFT contract.
///
/// Deploy this contract separately and call `set_reputation_nft` on the lending
/// contract to wire it up.  The `minter` registered here must be the lending
/// contract address.
/// Mint an excellent credit tier badge for a borrower.
/// Eligibility: credit score >= 850, >= 2 successful repayments, no defaults.
pub fn mint_excellent_badge(env: &Env, borrower: &Address) -> Result<(), ContractError> {
    // Check if already has badge
    if env
        .storage()
        .persistent()
        .has(&DataKey::ReputationNFTBadge(borrower.clone()))
    {
        return Ok(()); // Already minted
    }

    // Check eligibility: score >= 850
    let credit_score = env
        .storage()
        .persistent()
        .get::<DataKey, crate::types::CreditScore>(&DataKey::CreditScore(borrower.clone()))
        .ok_or(ContractError::InvalidAmount)?;

    if credit_score.score < 850 {
        return Err(ContractError::InvalidAmount);
    }

    // Check >= 2 successful repayments
    if credit_score.successful_repayments < 2 {
        return Err(ContractError::InvalidAmount);
    }

    // Check no defaults
    if credit_score.defaults > 0 {
        return Err(ContractError::InvalidAmount);
    }

    // Mint the badge
    let now = env.ledger().timestamp();
    let badge = ReputationNFTRecord {
        borrower: borrower.clone(),
        minted_at: now,
    };

    env.storage()
        .persistent()
        .set(&DataKey::ReputationNFTBadge(borrower.clone()), &badge);

    Ok(())
}

/// Burn an excellent credit tier badge on default.
pub fn burn_excellent_badge(env: &Env, borrower: &Address) {
    env.storage()
        .persistent()
        .remove(&DataKey::ReputationNFTBadge(borrower.clone()));
}

/// Check if a borrower has an excellent credit tier badge.
pub fn has_excellent_badge(env: &Env, borrower: &Address) -> bool {
    env.storage()
        .persistent()
        .has(&DataKey::ReputationNFTBadge(borrower.clone()))
}

/// Get the excellent badge record for a borrower.
pub fn get_excellent_badge(env: &Env, borrower: &Address) -> Option<ReputationNFTRecord> {
    env.storage()
        .persistent()
        .get(&DataKey::ReputationNFTBadge(borrower.clone()))
}

#[cfg(test)]
#[contract]
pub struct ReputationNftContract;

#[cfg(test)]
#[contractimpl]
impl ReputationNftContract {
    /// One-time setup: record the authorised minter (the lending contract).
    pub fn initialize(env: Env, minter: Address) {
        if env.storage().instance().has(&RepKey::Minter) {
            panic_with_error!(&env, ContractError::AlreadyInitialized);
        }
        env.storage().instance().set(&RepKey::Minter, &minter);
    }

    /// Mint one reputation point to `to`. Only callable by the registered minter.
    pub fn mint(env: Env, to: Address) {
        let minter: Address = env
            .storage()
            .instance()
            .get(&RepKey::Minter)
            .expect("not initialized");
        minter.require_auth();

        let score: u32 = env
            .storage()
            .persistent()
            .get(&RepKey::Score(to.clone()))
            .unwrap_or(0);
        env.storage()
            .persistent()
            .set(&RepKey::Score(to), &(score + 1));
    }

    /// Burn one reputation point from `from` (floor at 0). Only callable by the registered minter.
    pub fn burn(env: Env, from: Address) {
        let minter: Address = env
            .storage()
            .instance()
            .get(&RepKey::Minter)
            .expect("not initialized");
        minter.require_auth();

        let score: u32 = env
            .storage()
            .persistent()
            .get(&RepKey::Score(from.clone()))
            .unwrap_or(0);
        env.storage()
            .persistent()
            .set(&RepKey::Score(from), &score.saturating_sub(1));
    }

    /// Returns the reputation score for `addr`.
    pub fn balance(env: Env, addr: Address) -> u32 {
        env.storage()
            .persistent()
            .get(&RepKey::Score(addr))
            .unwrap_or(0)
    }
}

// ── Test helpers ──────────────────────────────────────────────────────────────
//
// The `ReputationNftContractClient` used in integration tests is auto-generated
// by `#[contractimpl]` above (available under `testutils` feature).  Tests can
// register `ReputationNftContract` directly:
//
//   let nft_id = env.register_contract(None, ReputationNftContract);
//
// No additional test-only wrapper is required.
